{
 "title": "Akamai CDN Delivery",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Akamai Time (Last)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "transferTimeMSec", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Akamai Time (Average)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "transferTimeMSec", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Origin Time (Last)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "turnAroundTimeMSec", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Origin Time (Average)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "turnAroundTimeMSec", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Akamai Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "transferTimeMSec", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Origin Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "turnAroundTimeMSec", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Locations",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "customer.geo.location", "id": "2", "settings": { "precision": "12" }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "field": "transferTimeMSec", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "customer.geo.country_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "customer.geo.region_code.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "customer.geo.city_name.keyword",
       "id": "5",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transferTimeMSec", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cliIP.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "transferTimeMSec", "id": "1", "type": "avg" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Hits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "totalBytes", "id": "1", "type": "sum" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cache Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cacheable",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Locations",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "customer.geo.location", "id": "2", "settings": { "precision": "12" }, "type": "geohash_grid" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "customer.geo.country_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "customer.geo.region_code.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      },
      {
       "field": "customer.geo.city_name.keyword",
       "id": "5",
       "settings": {
        "min_doc_count": "1",
        "missing": "-",
        "order": "desc",
        "orderBy": "1",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "cliIP.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Protocols",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "proto",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "TLS Version",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "tlsVersion",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "reqMethod",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Referer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "referer",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Devices",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.device.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "OSes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.os.full.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "user_agent.name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "URLs",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "reqHost",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "reqPath",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "queryStr",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Responses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 } },
  {
   "title": "Mime/Types",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rspContentType",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "statusCode",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Akamai Attempts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "edgeAttempts.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Akamai Codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "errorCode",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Akamai Rules Triggered",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "securityRules",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10m", "min_doc_count": "0" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}