apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: akamai-opensearch
  labels:
    app: opensearch-logstash
data:
  input-http.yml: |
    input {
      http {
        host => "0.0.0.0"
        port => 8080
        codec => json
      }
    }
    filter {
      json {
              source => "message"
              remove_field => ["message"]
            }
      if [securityRules] {
        mutate {
          split => { "securityRules" => "|" }
        }
        if [securityRules][0] {
                mutate {
                  add_field => { "securityPolicy" => "%{[securityRules][0]}" }
                }
        }
        if [securityRules][1] {
                mutate {
                  add_field => { "securityPolicyRules" => "%{[securityRules][1]}" }
                }
        }
        if [securityRules][2] {
                mutate {
                  add_field => { "securityPolicyBotRule" => "%{[securityRules][2]}" }
                }
        }
      }
      mutate {
              remove_field => ["[event]", "[user_agent]", "[http]", "[url]", "[host]"]
            }
      urldecode {
              field => "customField"
            }
      urldecode {
              field => "city"
            }
      urldecode {
              field => "state"
            }
      date {
              match => [ "reqTimeSec","UNIX" ]
              target => [ "@timestamp" ]
            }
      urldecode {
              field => "UA"
            }
      useragent {
              source => "UA"
            }
      geoip {
              ecs_compatibility => disabled
              source => "[cliIP]"
              target => "[customer][geo]"
            }
      geoip {
              ecs_compatibility => disabled
              source => "[edgeIP]"
              target => "[akamai][geo]"
            }
    }
    output {
      opensearch {
        hosts => ["http://opensearch-service:9200"]
        index => "ds2-akamai-%{+YYYY-MM-dd}"
      }
    }