apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: akamai-opensearch
  labels:
    app: opensearch-logstash
data:
  input-http.yml: |
    input {
      http {
        host => "0.0.0.0"
        port => 8080
      }
    }

    output {
      opensearch {
        hosts => ["http://opensearch-node1:9200", "http://opensearch-node2:9200"]
        index => "ds-getnet-%{+YYYY-MM-dd}"
      }
    }