apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-node1-deployment
  namespace: akamai-opensearch
  labels:
    app: opensearch-node1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-node1
  template:
    metadata:
      labels:
        app: opensearch-node1
    spec:
      containers:
      - name: opensearch-node1
        image: opensearchproject/opensearch:latest
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: cluster.name
          value: opensearch-cluster
        - name: node.name
          value: opensearch-node1
        - name: discovery.seed_hosts
          value: opensearch-node1,opensearch-node2
        - name: cluster.initial_cluster_manager_nodes
          value: opensearch-node1,opensearch-node2
        - name: "bootstrap.memory_lock"
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms1g -Xms1g"
        - name: "DISABLE_INSTALL_DEMO_CONFIG"
          value: "true"
        - name: "DISABLE_SECURITY_PLUGIN"
          value: "true"
        volumeMounts:
            - name: opensearch-data1-volume
              mountPath: /usr/share/opensearch/data
      initContainers:
          - name: fix-disk-permissions
            image: busybox:latest
            command: ["sh","-c","mkdir -p /usr/share/opensearchsearch/data && chown -R 1000:root /usr/share/opensearchsearch/data"]
            resources:
              limits:
                cpu: 100m
                memory: 32Mi
            volumeMounts:
            - name: opensearch-data1-volume
              mountPath: /usr/share/opensearchsearch/data
          - name: max-map-count-setter
            image: docker.io/bash:5.2.15
            resources:
              limits:
                cpu: 100m
                memory: 32Mi
            securityContext:
              privileged: true
              runAsUser: 0
            command: ['/usr/local/bin/bash', '-e', '-c', 'echo 262144 > /proc/sys/vm/max_map_count']
      volumes:
        - name: opensearch-data1-volume
          persistentVolumeClaim:
            claimName: akamai-opensearch-data1-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-node2-deployment
  namespace: akamai-opensearch
  labels:
    app: opensearch-node2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-node2
  template:
    metadata:
      labels:
        app: opensearch-node2
    spec:
      containers:
      - name: opensearch-node2
        image: opensearchproject/opensearch:latest
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: cluster.name
          value: opensearch-cluster
        - name: node.name
          value: opensearch-node2
        - name: discovery.seed_hosts
          value: opensearch-node1,opensearch-node2
        - name: cluster.initial_cluster_manager_nodes
          value: opensearch-node1,opensearch-node2
        - name: "bootstrap.memory_lock"
          value: "false"
        - name: "ES_JAVA_OPTS"
          value: "-Xms1g -Xms1g"
        - name: "DISABLE_INSTALL_DEMO_CONFIG"
          value: "true"
        - name: "DISABLE_SECURITY_PLUGIN"
          value: "true"    
        volumeMounts:
            - name: opensearch-data2-volume
              mountPath: /usr/share/opensearchsearch/data
      initContainers:
          - name: fix-disk-permissions
            image: busybox:latest
            command: ["sh","-c","mkdir -p /usr/share/opensearchsearch/data && chown -R 1000:root /usr/share/opensearchsearch/data"]
            resources:
              limits:
                cpu: 100m
                memory: 32Mi
            volumeMounts:
            - name: opensearch-data2-volume
              mountPath: /usr/share/opensearchsearch/data
          - name: max-map-count-setter
            image: docker.io/bash:5.2.15
            resources:
              limits:
                cpu: 100m
                memory: 32Mi
            securityContext:
              privileged: true
              runAsUser: 0
            command: ['/usr/local/bin/bash', '-e', '-c', 'echo 262144 > /proc/sys/vm/max_map_count']
      volumes:
        - name: opensearch-data2-volume
          persistentVolumeClaim:
            claimName: akamai-opensearch-data2-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-dashboards-deployment
  namespace: akamai-opensearch
  labels:
    app: opensearch-dashboards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-dashboards
  template:
    metadata:
      labels:
        app: opensearch-dashboards
    spec:
      containers:
      - name: opensearch-dashboards
        image: opensearchproject/opensearch-dashboards:latest
        ports:
        - containerPort: 5601
        env:
        - name: OPENSEARCH_HOSTS
          value: '["http://opensearch-node1:9200","http://opensearch-node2:9200"]'
        - name: "DISABLE_SECURITY_DASHBOARDS_PLUGIN"
          value: "true"
        - name: "SERVER_BASEPATH"
          value: "/logs"
        - name: "SERVER_REWRITEBASEPATH"
          value: "true"
        - name: "ES_JAVA_OPTS"
          value: "-Xms1g -Xms1g"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-logstash-deployment
  namespace: akamai-opensearch
  labels:
    app: opensearch-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-logstash
  template:
    metadata:
      labels:
        app: opensearch-logstash
    spec:
      containers:
      - name: opensearch-logstash
        image: opensearchproject/logstash-oss-with-opensearch-output-plugin
        ports:
        - containerPort: 8080
        volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/pipeline
      volumes:
          - name: config
            configMap:
              name: logstash-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-grafana-deployment
  namespace: akamai-opensearch
  labels:
    app: opensearch-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-grafana
  template:
    metadata:
      labels:
        app: opensearch-grafana
    spec:
      containers:
      - name: opensearch-grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: opensearch-grafana-volume
              mountPath: /etc/grafana/provisioning
      volumes:
          - name: grafana-config
            configMap:
              name: grafana-ini
          - name: opensearch-grafana-volume
            persistentVolumeClaim:
              claimName: akamai-grafana-data-claim