apiVersion: v1
kind: Service
metadata:
  name: opensearch-node1
  namespace: akamai-opensearch
spec:
  selector:
    app: opensearch-node1
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-node2
  namespace: akamai-opensearch
spec:
  selector:
    app: opensearch-node2
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
---
# Ingress service definition.
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards-service
  namespace: akamai-opensearch
  labels:
    app: opensearch-dashboards
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5601
      targetPort: 5601
  selector:
    app: opensearch-dashboards
---
# Ingress service definition.
apiVersion: v1
kind: Service
metadata:
  name: opensearch-logstash-service
  namespace: akamai-opensearch
  labels:
    app: opensearch-logstash
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: opensearch-logstash