apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akamai-opensearch-data1-claim
  namespace: akamai-opensearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: akamai-opensearch-data2-claim
  namespace: akamai-opensearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
